### ISSUE TITLE
Release on Ore? <3

### ISSUE THREAD

**Issue by parlough** [dags-/Plots#14]
I know a lot of people like to use plots plugins, so I would love to see this once finalized for API 7/7.1 on Ore as I suspect many others would as well.

**Comment by dags-** [comment]
I just make things for my own needs, and put them on Github if I think others might find them useful as-is or as decent starting points for their own projects.

Something like Ore obliges (forced to have a discussion thread, for example) more interaction, support and catering to requests, which I don't really have time for.

**Comment by parlough** [comment]
Fair enough, I appreciate your open sourcing of your projects though, so keep it up!
